version: '3.7'

services:
  db:
    image: mysql:8
    # to allow node mysql driver to conect with plain text password
    # https://github.com/docker-library/mysql/issues/454
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - '6000:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  api:
    build: .
    # needed for node conteiner to receive process signals such as Ctrl+C
    init: true
    depends_on:
      - db
    # There is a possibility that database container starts after api container
    # already initialized. This would cause api container to crash.
    # At some point db will finish initialization and api will start properly.
    # Api code can have unhandled exceptions which also will crash whole process
    # and this option gives oportunity to start process from scratch automatically.
    restart: always
    ports:
      - '5000:3000'
